"""assessment_engine_v2

Revision ID: b48a2418ac0e
Revises: 520610e195c0
Create Date: 2026-08-11 21:45:30.298390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'b48a2418ac0e'
down_revision: Union[str, None] = '520610e195c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


question_type_enum = postgresql.ENUM(
    'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'TRUE_FALSE', 'FILL_BLANK', name='question_type'
)
attempt_layout_enum = postgresql.ENUM('SCROLL', 'PAGED', name='attempt_layout')


def upgrade() -> None:
    bind = op.get_bind()
    question_type_enum.create(bind, checkfirst=True)
    attempt_layout_enum.create(bind, checkfirst=True)
    op.add_column('answers', sa.Column('selected_option_ids', sa.JSON(), nullable=True))
    op.add_column('answers', sa.Column('text_answer', sa.String(length=1000), nullable=True))
    op.add_column('attempts', sa.Column('layout', sa.JSON(), nullable=True))
    op.add_column('questions', sa.Column('question_type', question_type_enum, server_default='SINGLE_CHOICE', nullable=False))
    op.add_column('questions', sa.Column('accepted_answers', sa.JSON(), nullable=True))
    op.add_column('quizzes', sa.Column('negative_marking_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('quizzes', sa.Column('negative_marks_per_wrong', sa.Float(), server_default='0', nullable=False))
    op.add_column('quizzes', sa.Column('shuffle_questions', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('quizzes', sa.Column('shuffle_options', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('quizzes', sa.Column('available_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes', sa.Column('available_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quizzes', sa.Column('attempt_layout', attempt_layout_enum, server_default='SCROLL', nullable=False))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'attempt_layout')
    op.drop_column('quizzes', 'available_until')
    op.drop_column('quizzes', 'available_from')
    op.drop_column('quizzes', 'shuffle_options')
    op.drop_column('quizzes', 'shuffle_questions')
    op.drop_column('quizzes', 'negative_marks_per_wrong')
    op.drop_column('quizzes', 'negative_marking_enabled')
    op.drop_column('questions', 'accepted_answers')
    op.drop_column('questions', 'question_type')
    op.drop_column('attempts', 'layout')
    op.drop_column('answers', 'text_answer')
    op.drop_column('answers', 'selected_option_ids')
    op.execute('DROP TYPE IF EXISTS attempt_layout')
    op.execute('DROP TYPE IF EXISTS question_type')
    # ### end Alembic commands ###
